name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js 20.3.0
        uses: actions/setup-node@v2
        with:
          node-version: '20.3.0'

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          continue-on-error: true 
          install-command: npm install
          start: npm start
          browser: chrome

      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
